version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_work_db
    ports:
      - "8500:8500"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres